sudo: required

services:
	- docker

before_install:
	- docker build -t Shanger1/devops/mydockerfrontend -f Dockerfile.dev .

script:
	- docker run -e CI=true Shanger1/devops/mydockerfrontend yarn test
