sudo: required

services:
  - docker

before_install:
  - docker build -t shanger/my-frontend -f mydockerfrontend/Dockerfile.dev mydockerfrontend/.

script:
  - docker run -e CI=true shanger/my-frontend yarn test