kubectl delete service myredisservice
kubectl delete service mypostgresservice
kubectl delete service myapp-backend-clusterip
kubectl delete service myapp-frontend-clusterip
kubectl delete configMaps --all
kubectl delete deployments --all
kubectl delete pods --all
kubectl delete ingresses --all
kubectl delete pvc postgres-pvc
kubectl delete pv pv-volume1
kubectl delete sc local-storage
kubectl delete secret myapp-secret
